format = """
[  ]( fg:#87CEFA )\
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$rust\
$golang\
$php\
$time\
\n$character"""

[line_break]
disabled = true

[directory]
style = "fg:#87CEFA"
format = "[$path]($style)"
truncation_length = 0
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ":: "
style = "fg:#f1502f"
format = '[[ $symbol $branch ](fg:#f1502f)]($style)'

[git_status]
style = "fg:#f1502f"
format = "[[$all_status$ahead_behind](fg:#f1502f)]($style)"

[fill]
symbol = " "

[nodejs]
style = "fg:#6ca35e"
format = "[$symbol($version)]($style)"

[rust]
symbol = ""
style = "fg:#6ca35e"
format = "[$symbol($version)]($style)"

[golang]
symbol = ""
style = "fg:#6ca35e"
format = "[$symbol($version)]($style)"

[php]
symbol = ""
style = "fg:#6ca35e"
format = "[$symbol($version)]($style)"

[time]
disabled = false
style = "fg:#00ff00"
format = "[   $time]($style)"

[character]
success_symbol = "[󰭟 ](bold green)"
error_symbol = "[󰭟 ](bold red)"

#[time]
#disabled = false
#time_format = "%R" # Hour:Minute Format
#style = "bg:#1d2230"
#format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
